### ISSUE TITLE
Adicionar readme.

### ISSUE THREAD

**Issue by midnightbattles** [midnightbattles/blog#1]
# Requisitos:

* idioma pt_br
* Título e breve descrição do projeto
* Pré-requisitos
    - Versão do Python
* Guia de instalação
* Licença
* usar [markdown](https://github.com/tchapi/markdown-cheatsheet)
 
**Links com exemplos de readme**

https://github.com/dbader/readme-template
https://github.com/matiassingers/awesome-readme

[Como escrever um README.md sensacional](https://dev.to/reginadiana/como-escrever-um-readme-md-sensacional-no-github-4509)

**Comment by andreztz** [comment]
Posso trabalhar nessa issue?

**Comment by midnightbattles** [comment]
@andreztz legal o readme.
